app:
  baseUrl: https://${APP_DOMAIN}

backend:
  baseUrl: https://${APP_DOMAIN}
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: './data/backstage.sqlite' # Database file location
  cors:
    origin: https://${APP_DOMAIN}

# For a demo, pre-load some example components
catalog:
  locations:
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml
