app:
  # This MUST match the actual URL provided by Cloud Run
  baseUrl: https://backstage-demo-878837935390.us-central1.run.app

backend:
  baseUrl: https://backstage-demo-878837935390.us-central1.run.app
  listen:
    host: 0.0.0.0 # Allows Cloud Run to route traffic to the container
    port: 7007
  
  database:
    client: better-sqlite3
    connection: './backstage.sqlite'

  cors:
    # This prevents the "Cross-Origin" errors that stop the UI from loading
    origin: https://backstage-demo-878837935390.us-central1.run.app
    methods: [GET, POST, PUT, DELETE]
    credentials: true

  auth:
    keys:
      - secret: ${BACKEND_SECRET}

catalog:
  import:
    entityFilename: catalog-info.yaml
    recursive: true
  locations:
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-entities.yaml
      rules:
        - allow: [Component, System, API, Group, User, Resource, Location]
